### ISSUE TITLE
Error when run server.js

### ISSUE THREAD

**Issue by khoint0210** [compewter/CopyCat#2]
After i typed 

node server.js (in root mode)

this happen 
/root/CopyCat/utils/session.js:4
let sessionCookie = process.env.SESS_COOKIE;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/CopyCat/server.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by compewter** [comment]
That looks like an error thrown by older versions of node. What version of node are you using?

Try upgrading node to version 6+ and see if that doesn't fix your issue.

**Comment by khoint0210** [comment]
Thanks, man work like a charm I forgot to check the version of node on my linux machine
